complete -c tailscale --no-files --condition "__fish_use_subcommand" --arguments bugreport --description "Print a shareable identifier to help diagnose issues"
complete -c tailscale --no-files --condition "__fish_use_subcommand" --arguments down      --description "Disconnect from Tailscale"
complete -c tailscale --no-files --condition "__fish_use_subcommand" --arguments ip        --description "Show current Tailscale IP address(es)"
complete -c tailscale --no-files --condition "__fish_use_subcommand" --arguments logout    --description "Disconnect from Tailscale and expire current node key"
complete -c tailscale --no-files --condition "__fish_use_subcommand" --arguments netcheck  --description "Print an analysis of local network conditions"
complete -c tailscale --no-files --condition "__fish_use_subcommand" --arguments ping      --description "Ping a host at the Tailscale layer, see how it routed"
complete -c tailscale --no-files --condition "__fish_use_subcommand" --arguments status    --description "Show state of tailscaled and its connections"
complete -c tailscale --no-files --condition "__fish_use_subcommand" --arguments up        --description "Connect to your Tailscale network"
complete -c tailscale --no-files --condition "__fish_use_subcommand" --arguments version   --description "Print Tailscale version"
complete -c tailscale --no-files --condition "__fish_use_subcommand" --arguments web       --description "Run a web server for controlling Tailscale"

complete -c tailscale --no-files --condition "__fish_use_subcommand" --arguments cert      --description "get TLS certs"
complete -c tailscale --no-files --condition "__fish_use_subcommand" --arguments file      --description "Send or receive files"
